### ISSUE TITLE
Other distributions of Java

### ISSUE THREAD

**Issue by Kore-Development** [dscalzi/HeliosLauncher#151]
Does Helios Launcher support other distributions of Java such as Amazon Corretto or is it just OpenJDK or Oracle Java?

**Comment by GeekCornerGH** [comment]
Corretto is supported. If you are on a mac, and you don't have Java, Corretto will be downloaded instead of AdoptOpenJDK in Windows and Linux

**Comment by gamernitro999** [comment]
yes that supported cause openJDK is based on oracle java jdk idk what is corretto but with what you say i think that same

**Comment by dscalzi** [comment]
You can use whatever variant you want as long as the game starts up and runs properly. We know it works with AdoptOpenJDK, so that's what the launcher pulls from. This is not a hard requirement. Hard requirements on java version would come from either Mojang, Forge, or any mods you use.

The launcher prefers Coretto on macOS because it mitigates an error with Optifine. That is explained in great detail here https://github.com/dscalzi/HeliosLauncher/issues/70
