### ISSUE TITLE
Switch screenshots to other launcher

### ISSUE THREAD

**Issue by ghost** [dscalzi/HeliosLauncher#190]
Now that WesterosCraft Launcher has deprecated their launcher using Helios, it's best to switch the screenshots to a project that is actually still recommending Helios Launcher such as ArdaCraft

**Comment by dscalzi** [comment]
I believe WesterosCraft's decision to discontinue their Helios Launcher instance is due to a lack of technical resources that can keep their fork up to date with master. If you look at their GitHub, they havent pulled any patches down in about two years. It appears they've also discontinued their old launcher (the one Helios replaced).

Recall, Helios Launcher started as a custom launcher for WesterosCraft. It was rebranded to Helios later, since many third-party servers liked the platform and adopted it for their own uses. As such, we don't necessarily have to change the default screenshots at this time.

Thank you for the information

**Comment by SNDST00M** [comment]
Understood, didn't know it started as a WesterosCraft project

**Comment by drori200** [comment]
> I believe WesterosCraft's decision to discontinue their Helios Launcher instance is due to a lack of technical resources that can keep their fork up to date with master. If you look at their GitHub, they havent pulled any patches down in about two years. It appears they've also discontinued their old launcher (the one Helios replaced).
> 
> Recall, Helios Launcher started as a custom launcher for WesterosCraft. It was rebranded to Helios later, since many third-party servers liked the platform and adopted it for their own uses. As such, we don't necessarily have to change the default screenshots at this time.
> 
> Thank you for the information

From a quick google search it seems like they moved over to GDLuancher

**Comment by dscalzi** [comment]
Yes, which is a launcher that does not really require any maintenance. It makes sense to use that if you lack technical resources.

**Comment by SNDST00M** [comment]
Microsoft account support was a big reason, there were many questions about it and it would probably have gone through by 2022.
