### ISSUE TITLE
the launcher stays at 100% and does not advance

### ISSUE THREAD

**Issue by VonDefiant** [dscalzi/HeliosLauncher#250]
![imagen](https://user-images.githubusercontent.com/91977851/193333947-a37eccb4-7cd5-4d9f-9cd1-cc525b3f88a7.png)

my launcher stays in that part and it's already advancing further and I already deleted the appdata folder and nothing :c

**Comment by DinkyPerson** [comment]
me, too. But 99%

**Comment by christophe-merlen** [comment]
Hello,

your problem may be due to the distribution index. Check if the distribution index lists all the files that the launcher must download to launch the game and that these files are downloadable by the launcher.

If this answered your questions, do not hesitate to close the issue. This will help the creator by decreasing the amount of issues to be answered.
