### ISSUE TITLE
Server Ip

### ISSUE THREAD

**Issue by ghost** [dscalzi/HeliosLauncher#277]
Hello, I changed the code of the whole program so that I could put my own server which is in 1.18.2, and suddenly I redid the Minecraft download system, I created a release and the problem is that it doesn't work, the launcher always opens, but when minecraft launches, it's always in 1.12.2 with the mods and it connects to your server, and on the launcher, its ping your server
How can I fix this?

Here is the link of my github project : https://github.com/MrPiano5454/hardiumLauncher

**Comment by dscalzi** [comment]
Change this url to your own distribution. You are using the old westeroscraft distribution, so that's why you're seeing their server.
https://github.com/MrPiano5454/hardiumLauncher/blob/master/app/assets/js/distromanager.js#L550

Use [Nebula ](https://github.com/dscalzi/Nebula) to generate a distribution
