### ISSUE TITLE
Binary discrepancy between expected input claas aad and actual class

### ISSUE THREAD

**Issue by OfficialCRUGG** [dscalzi/HeliosLauncher#43]
I tried on making my own instance of the HeliosLauncher for my own Modpack (with self hosted Jar Files; updated all checksums and sizes) however I get those two errors:
```
[Minecraft] [19:17:30] [main/FATAL]: There is a binary discrepancy between the expected input class aad (aad) and the actual class. Checksum on disk is f4e77106, in patch 5753cef1. Things are probably about to go very wrong. Did you put something into the jar file?

[Minecraft] [19:17:30] [main/FATAL]: The game is going to exit, because this is a critical error, and it is very improbable that the modded game will work, please obtain clean jar files.
```
How can I fix this or at least get some more information to fix this issue more easily?

**Comment by CptPlastic** [comment]
If you are going to mod this It would be nice if there was a clean launcher with the ability to turn off forge asset management. It basically cached your mod IE Checksum on disk is f4e77106, in patch 5753cef1 they need to match. If they do not it trys to fix that. You should review https://github.com/dscalzi/HeliosLauncher/blob/master/app/assets/js/assetguard.js 
There looks to be a developer mode you can put things into so that it stops trying to pull stuff from the website.

**Comment by OfficialCRUGG** [comment]
I don't really understand your reply

**Comment by dscalzi** [comment]
1. Which version of forge are you using.
2. Make sure you've installed all the files correctly. The error means that an expected file has an invalid checksum. This is used to make sure that the saved file is exactly what it's expecting.
