### ISSUE TITLE
Disable Dropdown mod function?

### ISSUE THREAD

**Issue by GeekCornerGH** [dscalzi/HeliosLauncher#49]
Hello.
I would like to deactivate the Mod Dropdown function. How to do it?
Thanks in advance for your answer.
Have a good day.
GeekCorner

**Comment by Rob5Underscores** [comment]
Which dropdown do you mean? Can you provide a photo?

**Comment by GeekCornerGH** [comment]
@Rob5Underscores the function which allows you to add Customs mods

**Comment by Rob5Underscores** [comment]
Presuming you mean the drop-in mod container?

To hide this element you could simply add styling to hide it.

Like `<div id="settingsDropinModsContainer" style="display: none">` at the following place: https://github.com/dscalzi/HeliosLauncher/blob/96db60791249b6c70c5eb295dc32fe591320326f/app/settings.ejs#L119

**Comment by GeekCornerGH** [comment]
Yeah @Rob5Underscores but the "mods" folder remains present.

**Comment by Rob5Underscores** [comment]
You will need to stop the validation (and creation) of the drop-in mods directory - this is done in /assets/js/scripts/settings.js such as:
https://github.com/dscalzi/HeliosLauncher/blob/96db60791249b6c70c5eb295dc32fe591320326f/app/assets/js/scripts/settings.js#L696

Not sure what the purpose of your change if someone wants to use their own mod with your launcher, removing the folder is unlikely to stop them!

Since this isn't an issue, I would suggest closing it and seeking further help on the Aventium Softworks discord.

**Comment by GeekCornerGH** [comment]
I dont have Discord, so I cant ask for that feature. Otherwise, your bits of code look interesting. Thank you.
