### ISSUE TITLE
macOS - Disabling "Launch in Fullscreen." causes exception which stops Minecraft from launching

### ISSUE THREAD

**Issue by mitchmikusek** [dscalzi/HeliosLauncher#70]
When launching the application on macOS, if the "Launch in Fullscreen" configuration option is disabled, the following exception is thrown.
```
java[58752:2567192] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff36405d07 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6ef905bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3642e50c -[NSException raise] + 9
	3   AppKit                              0x00007fff3363524c -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
	4   AppKit                              0x00007fff3365f94e -[NSThemeFrame setStyleMask:] + 137
	5   AppKit                              0x00007fff3365f79c __25-[NSWindow setStyleMask:]_block_invoke + 1908
	6   AppKit                              0x00007fff3365efce NSPerformVisuallyAtomicChange + 132
	7   AppKit                              0x00007fff3365eed9 -[NSWindow setStyleMask:] + 184
	8   liblwjgl.dylib                      0x00000001293f0ee2 Java_org_lwjgl_opengl_MacOSXDisplay_nSetResizable + 82
	9   ???                                 0x00000001166b2407 0x0 + 4671087623
	10  ???                                 0x00000001166a1ffd 0x0 + 4671021053
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Current workaround is to simply enable fullscreen and the app works.

**Comment by mitchmikusek** [comment]
Not familiar enough to know a fix, but I seen many mentions regarding issue with the spawning of another window off the main thread / outside the event loop.

**Comment by dscalzi** [comment]
@mitchmikusek I will try to look into this tonight. Does it happen on all versions of the game or just a specific one?

**Comment by mitchmikusek** [comment]
Hey there @dscalzi , I'll verify that I see the error consistently across a variety of versions I have access to. You can also ping me in discord @catsensei if you need me to test a branch build

**Comment by mitchmikusek** [comment]
Tested a couple versions, WesterosCraft Prod 1.11.2, WesterosCraft Test 1.12.2, 1.12.2 on a Fork I support and 1.15.2 _Vanilla_ on a fork I support

Only one that worked was the `Vanilla` version here which I think runs 1.15.2 - https://github.com/MOONMOONOSS/HeliosLauncher/blob/master/app/assets/distribution.json#L403

**Comment by dscalzi** [comment]
Appears to be caused by https://github.com/AdoptOpenJDK/openjdk-support/issues/101

**Comment by dscalzi** [comment]
This issue really bothers me because it seems to be caused by AdoptOpenJDK updating the Xcode SDK. That seems to have caused an issue in lwjgl, the version of which is frozen as neither forge nor minecraft are supporting versions below a certain threshold.  This is bound to happen with more aspects of the game as other software moves forwards while old MC versions are frozen. There are several courses of action, neither or which I particularly want to take.

1. Report issue to lwjgl and hope they patch the older version. We then need to swap the version mojang lists for the patched version. (Dont want to do this at all).
2. Use an older version of the JDK permanently on macOS. I don't want to do this either, it opens the door to security vulnerabilities and is generally awful.
3. Use Mojang's JDK (old, 8_u20) that they ship with their launcher. This is nearly impossible to do without writing any native code. The lzma binary they ship it with is too large to decompress in nodejs. We can't write a Java library to decompress it because.. we dont have java on the PC yet (we're literally downloading java). The only option is to use a native decompression which adds many layers of complexity that I don't want to add to this. Just to name a few:
  * Platform builds for windows will no longer work on the travis linux vm. A new job would need to be setup on Appveyor.
  * Maintenance would now include a C++ library with Node.js bindings.
  * If Mojang ever pulls the plug and bumps to Java 11 this is useless and obsolete.

This is just a harbinger of many more road blocks older MC versions will face as time goes on. This may be an issue with AdoptOpenJDK only now (not sure if this is still even the case), but what happens when Corretto, Oracle, Redhat, etc bump the Xcode versions on their JDK. What happens when other aspects of the software update causing unrelated breakages?

The fix to persue may be to disable automatic java processing on affected versions and instructing users to install outdated JDKs at their own risk.

The IDEAL fix is to stop modding for old versions.

**Comment by dscalzi** [comment]
Further test cases from the OpenJDK thread have indicated it may be an issue with Optifine+Forge (or just Forge itself). If this is the case a fix would involve patching forge from 1.8-1.12(?) which wont happen. Maybe if someone told them that > half the modded community is stuck on these old versions they would bend..

**Comment by dscalzi** [comment]
Another workaround would be to use Corretto 8 as they're on an older version of Xcode. If they have plans to update then this is only a temporary fix.

```
https://corretto.aws/[latest/latest_checksum]/amazon-corretto-[corretto_version]-[cpu_arch]-[os]-[package_type].[file_extension]
```

**Comment by dscalzi** [comment]
Using corretto 8 is the option we'll go with for now. This will probably come up again in the future when they update their Xcode version. This warning is already present:

```
WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007fff32319607 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 378
	1   AppKit                              0x00007fff3241c43f -[NSThemeFrame setStyleMask:] + 137
	2   AppKit                              0x00007fff3241c292 __25-[NSWindow setStyleMask:]_block_invoke + 1896
	3   AppKit                              0x00007fff322d1970 NSPerformVisuallyAtomicChange + 132
	4   AppKit                              0x00007fff3241badf -[NSWindow setStyleMask:] + 184
	5   liblwjgl.dylib                      0x0000000120e8bee2 Java_org_lwjgl_opengl_MacOSXDisplay_nSetResizable + 82
	6   ???                                 0x0000000110902407 0x0 + 4572849159
	7   ???                                 0x00000001108f1ffd 0x0 + 4572782589
)
```

**Comment by dscalzi** [comment]
@jacobgranberry Consider updating your fork, https://github.com/dscalzi/HeliosLauncher/commit/9a2c1fd9b94471838968165b4b3c7493e772b598 will fix the macOS issues your users are having for now.

**Comment by dscalzi** [comment]
Update: https://github.com/sp614x/optifine/issues/4824#issuecomment-804947104
