### ISSUE TITLE
Can i make a modpack and use it?

### ISSUE THREAD

**Issue by lilRufi** [dscalzi/HeliosLauncher#92]

**Comment by TheFlash787** [comment]
Of course. You'll need to setup and use https://github.com/dscalzi/Nebula to configure a distribution.json which your launcher will then download. The distribution.json contains everything regarding what is available to download on the launcher, including modpacks and all their necessary files.

Whilst you will definitely need to read the documentation inside of the readme, this is a screenshot of the section that describes how you actually make a new 'server' (modpack) inside of the launcher. Since this is technically a server launcher, a lot of the terms will use 'server' instead of 'modpack', but you can just disable the auto connect if you don't want to take them to a server when they load up the modpack.

![image](https://user-images.githubusercontent.com/25883284/89744629-d28b6b00-daa6-11ea-8ca5-246177ed0770.png)

I hope that helps

**Comment by ValkyrieHD42** [comment]
Hello !
Does the mods from the distribution.json have to be uploaded online ?
For exemple if I want my friends to use my modpack, for now the link of mods are local but if I want them to download my modpack I need to change the links of mods right?

**Comment by TheFlash787** [comment]
@ValkyrieHD42 Definitely, yeah. You'll need to have a CDN/web-server of some kind where the distribution.json is stored alongside the server/repo files that are necessary (`repo` folder is generated by Nebula, it's necessary for Forge and it's libraries).

If you upload all your launcher-modpack files to a webserver called `valkyriehd.com` let's say, and inside of a folder `launcher/upload/` (and is accessable via `http(s)://valkyriehd.com/launcher/upload`), you'll want to make sure that your launcher is looking for the distribution file there also. `https://valkyriehd.com/launcher/upload/distribution.json` (purely an example)

It may take a little while to get the hang of, but we're all more than happy to help. I would recommend creating a new issue or joining the Discord server though https://discord.gg/jPXU77c
